# For more see https://gohugo.io/content-management/menus/

main:                     # sections in the website sidebar
  - identifier: english   # section id
    name: English         # section display title
    url: /                # path to the section
    weight: 1             # order of sections

  - identifier: turkce
    name: Türkçe
    url: /turkce/
    weight: 2